# Generated by Django 5.2.12 on 2026-05-12 17:58

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructions',
            field=models.FileField(blank=True, null=True, upload_to='assignment_instructions/', validators=[courses.models.validate_file_size, courses.models.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(upload_to='assignment_submissions/', validators=[courses.models.validate_file_size, courses.models.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', validators=[courses.models.validate_file_size, courses.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='instructors/', validators=[courses.models.validate_file_size, courses.models.validate_image_extension]),
        ),
    ]
